//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
namespace AppForMovies.Models
{
    public class Customer : ApplicationUser
    {
        public virtual IList<Purchase> Purchases
        {
            get;
            set;
        }


    }
}
