//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;


namespace AppForMovies.Models { 
    public class PurchaseItem
    {
        [Key]
        public int Id
        {
            get;
            set;
        }

        [ForeignKey("MovieId")]
        public virtual Movie Movie
	    {
		    get;
		    set;
	    }

        [Range(1,Double.MaxValue, ErrorMessage ="You must provide a valid quantity")]
        public virtual int Quantity
        {
            get;
            set;
        }

        public virtual int MovieId
        {
            get;
            set;
        }
        [ForeignKey("PurchaseId")]
        public virtual Purchase Purchase
	    {
		    get;
		    set;
	    }

        public virtual int PurchaseId
        {
            get;
            set;
        }

        public override bool Equals(object obj)
        {
            return obj is PurchaseItem item &&
                   Id == item.Id &&
                   EqualityComparer<Movie>.Default.Equals(Movie, item.Movie) &&
                   Quantity == item.Quantity &&
                   MovieId == item.MovieId &&
                   EqualityComparer<Purchase>.Default.Equals(Purchase, item.Purchase) &&
                   PurchaseId == item.PurchaseId;
        }
    }

}